version: '3.5'

services:
  mongo:
    image: mongo:3.4.18
    container_name: indyscan-mongo
    networks:
    - indynet
    volumes:
    -  indyscandb:/data/db
    ports:
    - 27017:27017

  indyscan:
    image: pstas/indyscan:latest
    container_name: indyscan-webapp
    networks:
    - indynet
    depends_on:
    - mongo
    environment:
    - URL_MONGO=mongodb://mongo.indynet:27017
    ports:
    - '3000:3000'

  indyscan-daemon:
    image: pstas/indyscan-daemon:latest
    container_name: indyscan-daemon
    networks:
    - indynet
    depends_on:
    - mongo
    environment:
    - URL_MONGO=mongodb://mongo.indynet:27017

volumes:
  indyscandb:
    external: false

networks:
  indynet:
    name: indynet
    driver: bridge
