version: '3.5'

services:

  mongo:
    image: mongo:3.4.18
    container_name: indyscan-mongo
    networks:
      - indynet
    volumes:
      -  indyscandb:/data/db
    ports:
      - 27999:27017

  indyscan-daemon:
    image: ${DAEMON_IMAGE}
    container_name: indyscan-daemon
    volumes:
      - ${MOUNTED_POOL_DIR}:/home/indyscan/.indy_client/pool
    network_mode: host
    depends_on:
      - mongo
    environment:
      - URL_MONGO=mongodb://localhost:27999
      - INDY_NETWORKS=${INDY_NETWORKS}
      - SCAN_MODE=${SCAN_MODE}

  indyscan:
    image: ${WEBAPP_IMAGE}
    container_name: indyscan-webapp
    networks:
      - indynet
    depends_on:
      - mongo
    environment:
      - URL_MONGO=mongodb://mongo.indynet:27017
      - INDY_NETWORKS=${INDY_NETWORKS}
      - WEBAPP_PORT=5050
    ports:
      - '5050:5050'

volumes:
  indyscandb:
    external: false

networks:
  indynet:
    name: indynet
    driver: bridge
